language: c
compiler:
- gcc
- clang
os:
- linux
- osx
before_install:
- sudo apt-get install libssl-dev
- sudo apt-get install liblua5.1-dev
script: make
notifications:
  slack:
    secure: k1GG7xFMgcLemnI0LxK0Qw2mukjmTKloHOyHI1wljer7GdOGy8icbaI6n7t1PCZ7MDYSmeQ8MFH5XbaUJT1lVkZYe1MNEsT3dpdDgAHBSk5dAu+5ZvFvoDZpRe7WS8X/mEThGgV1sQY1eKFVW8iVhVxLsSiaFPSWz1z/gGryhK4=
